# Generated by Django 3.1.7 on 2021-04-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='True', max_length=40),
        ),
    ]
